# -*- coding: utf-8 -*-
"""bharat intern 2(ml).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1212QVyVw9QVUvoI0wzZKQMaDcu7D344S
"""

import pandas as pd
import numpy as npfrom sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt

data = pd.read_csv('https://raw.githubusercontent.com/aniruddhachoudhury/Red-Wine-Quality/master/winequality-red.csv')
data

X = data.drop('quality', axis=1)  # Features
y = data['quality']
X
y

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train
X_test
y_train
y_test

model = LinearRegression()
model.fit(X_train, y_train)
model

y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'Mean Squared Error: {mse:.2f}')
print(f'R-squared: {r2:.2f}')

plt.scatter(y_test, y_pred)
plt.xlabel('Actual Wine Quality')
plt.ylabel('Predicted Wine Quality')
plt.title('Actual vs. Predicted Wine Quality')
plt.show()