# -*- coding: utf-8 -*-
"""BHARAT INTERN (ML)1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bKAtTmEzx7x9fWun1ocsfxvPb2D5Ac9I
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegressionR
from sklearn.metrics import mean_squared_error, r2_scoreR

data = pd.read_csv('https://raw.githubusercontent.com/huseinzol05/Stock-Prediction-Models/master/dataset/FB.csv')
data

data.head()

X = data['Open'].values.reshape(-1, 1)
y = data['High'].values
print(y)
X_train,X_test,y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)
print(X_train)
print(X_test)
print(y_train)
print(y_test)

model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(y_pred)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f"Mean Squared Error: {mse:.2f}")
print(f"R-squared (R2) Score: {r2:.2f}")

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f"Mean Squared Error: {mse:.2f}")
print(f"R-squared (R2) Score: {r2:.2f}")
plt.scatter(y_test, y_pred)
plt.xlabel('Actual Prices')
plt.ylabel('Predicted Prices')
plt.title('House Price Prediction')
plt.show()